version: '3'
services:
  node:
    build: .
    ports:
      - 5000:5000
      - 3000:3000
    command: ['npm', 'run', 'dev']
    volumes:
      - ./:/usr/src/app
    links:
      - mongodb

  mongodb:
    image: mongo:4.2.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: game
      MONGO_INITDB_ROOT_PASSWORD: welcome12
